alias gco "git checkout"
alias gcob "git checkout -b"
alias gcl "git clone"
alias ga "git add"
alias gaa "git add --all"
alias gc "git commit"
alias gpsh "git push"
alias gpll "git pull"
alias gb "git branch"
alias gm "git merge"
alias gs "git status"

